### ISSUE TITLE
更换评论区实现说明

### ISSUE THREAD

**Issue by FZQ0003** [FZQ0003/FZQ0003.github.io#16]
原评论区为基于Issues的Gitalk实现，存在索要过多权限的问题。  
新评论区打算采用基于Discussions的Giscus。  
所有评论区对应Issues已经转为Discussions，并将在近期转移到新仓库。  
同时会将博客迁移至[blog.fqilin.top](//blog.fqilin.top)，并开放新的仓库。  
原仓库另作他用。

**Comment by FZQ0003** [comment]
这是给评论区的：

评论区不可用。不要在这里评论，请到仓库Discussions评论。

详细信息请看这里：#16

**Comment by hacheyz** [comment]
我就要评论😋

**Comment by FZQ0003** [comment]
评论区实现更新完毕。
